server:
  port: 8881
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/gnaoussi/config-repo
          search-paths: cart,product,comment,order,payment,user
          username: gervais.naoussi@alithya.com
          password: ss2017si!* 